export enum ConfigKeys {
  // app
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  RATE_LIMIT_TTL = 'RATE_LIMIT_TTL',
  RATE_LIMIT_MAX = 'RATE_LIMIT_MAX',
  API_VERSION_PREFIX = 'API_VERSION_PREFIX',
  API_DEFAULT_VERSION = 'API_DEFAULT_VERSION',
  // jwt
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  // super admin
  SUPER_ADMIN_EMAIL = 'SUPER_ADMIN_EMAIL',
  SUPER_ADMIN_PASSWORD = 'SUPER_ADMIN_PASSWORD',
  //redis
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  CACHE_TTL = 'CACHE_TTL',
  CACHE_MAX_ITEMS = 'CACHE_MAX_ITEMS',
  // database
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_TYPE = 'DB_TYPE',
}
