export enum ConfigKeys {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  GLOBAL_PREFIX = 'GLOBAL_PREFIX',
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  RATE_LIMIT_TTL = 'RATE_LIMIT_TTL',
  RATE_LIMIT_MAX = 'RATE_LIMIT_MAX',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USER = 'DB_USER',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  DB_TYPE = 'DB_TYPE',
}
